/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"

bool_t
xdr_calculadora (XDR *xdrs, calculadora *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->numero1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->numero2))
		 return FALSE;
	return TRUE;
}
