/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct calculadora {
	int numero1;
	int numero2;
};
typedef struct calculadora calculadora;

#define CALCU_PROG 0x31111111
#define CALCU_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define Suma 1
extern  int * suma_1(calculadora *, CLIENT *);
extern  int * suma_1_svc(calculadora *, struct svc_req *);
#define Resta 2
extern  int * resta_1(calculadora *, CLIENT *);
extern  int * resta_1_svc(calculadora *, struct svc_req *);
#define Multiplicacion 3
extern  int * multiplicacion_1(calculadora *, CLIENT *);
extern  int * multiplicacion_1_svc(calculadora *, struct svc_req *);
#define Division 4
extern  float * division_1(calculadora *, CLIENT *);
extern  float * division_1_svc(calculadora *, struct svc_req *);
extern int calcu_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define Suma 1
extern  int * suma_1();
extern  int * suma_1_svc();
#define Resta 2
extern  int * resta_1();
extern  int * resta_1_svc();
#define Multiplicacion 3
extern  int * multiplicacion_1();
extern  int * multiplicacion_1_svc();
#define Division 4
extern  float * division_1();
extern  float * division_1_svc();
extern int calcu_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_calculadora (XDR *, calculadora*);

#else /* K&R C */
extern bool_t xdr_calculadora ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
