/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"


void
calcu_prog_1(char *host, char *num1, char *num2)
{
	CLIENT *clnt;
	int  *result_1;
	calculadora  suma_1_arg;
	int  *result_2;
	calculadora  resta_1_arg;
	int  *result_3;
	calculadora  multiplicacion_1_arg;
	float  *result_4;
	calculadora  division_1_arg;

#ifndef	DEBUG

	long int arr2[2]; /* Codigo añadido por programador */
		arr2[0] = strtol(num1, NULL, 10); /* Codigo añadido por programador */
		arr2[1] = strtol(num2, NULL, 10); /* Codigo añadido por programador */
	/* Codigo añadido por programador */
	division_1_arg.numero1 = multiplicacion_1_arg.numero1 = resta_1_arg.numero1 = suma_1_arg.numero1 = arr2[0]; 
	division_1_arg.numero2 = multiplicacion_1_arg.numero2 = resta_1_arg.numero2 = suma_1_arg.numero2 = arr2[1]; 

	clnt = clnt_create (host, CALCU_PROG, CALCU_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	
	static int opc, opc2;
	do{
	
	printf("-------------------------\n");
	printf("    CALCULADORA\n");
	printf("-------------------------\n");
	printf("1. Suma \n");
	printf("2. Resta \n");
	printf("3. Multiplicacion \n");
	printf("4. Division \n");
	printf("5. Salir \n");
	printf("\n Ingrese una opcion: \n -> ");
	
	scanf("%i", &opc);
	
	//do{
	switch(opc){
	
		case 1: 
			do{
				result_1 = suma_1(&suma_1_arg, clnt);
				if (result_1 == (int *) NULL) {
					clnt_perror (clnt, "call failed");
				}
				
				printf("La suma de %d + %d es %d\n", suma_1_arg.numero1,
					suma_1_arg.numero2, *result_1); /* Codigo añadido por programador */
				printf("\nIngrese el numero 1 para continuar\n -> ");
				scanf("%i", &opc2);
				printf("\n");
		        }while(opc2 != 1);
			system("clear");
			printf("\n");
			break;
		case 2:
			do{
				result_2 = resta_1(&resta_1_arg, clnt);
				if (result_2 == (int *) NULL) {
					clnt_perror (clnt, "call failed");
				}

				printf ("La resta de %d - %d es %d\n", resta_1_arg.numero1,
					resta_1_arg.numero2, *result_2); /* Codigo añadido por programador */
				printf("\nIngrese el numero 1 para continuar\n -> ");
				scanf("%i", &opc2);
				printf("\n");
			}while(opc2 != 1);
			system("clear");
			printf("\n");
				break;
		case 3:
			do{
				result_3 = multiplicacion_1(&multiplicacion_1_arg, clnt);
				if (result_3 == (int *) NULL) {
					clnt_perror (clnt, "call failed");
				}

				printf ("La multiplicacion de %d * %d es %d\n", multiplicacion_1_arg.numero1,
					multiplicacion_1_arg.numero2, *result_3); /* Codigo añadido por programador */
				printf("\nIngrese el numero 1 para continuar\n -> ");
				scanf("%i", &opc2);
				printf("\n");
			}while(opc2 != 1);
			system("clear");
			printf("\n");
				printf("\n");
			break;
		case 4:
			do{
				result_4 = division_1(&division_1_arg, clnt);
				if (result_4 == (float *) NULL) {
					clnt_perror (clnt, "call failed");
				}

				printf ("La division de %d * %d es %f\n", division_1_arg.numero1,
					division_1_arg.numero2, *result_4); /* Codigo añadido por programador */
				printf("\nIngrese el numero 1 para continuar\n -> ");
				scanf("%i", &opc2);
				printf("\n");
			}while(opc2 != 1);
			system("clear");
			printf("\n");
			break;
	}

	}while(opc != 5);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	char *num1, *num2;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	num1 = argv[2];
	num2 = argv[3];
	calcu_prog_1 (host,num1,num2);
exit (0);
}
