/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

int *
suma_1_svc(calculadora *argp, struct svc_req *rqstp)
{
	printf("-------------------------\n");
	printf("    SUMA\n");
	printf("-------------------------\n");
	static int  result;

	/*
	 * insert server code here
	 */
	result = argp -> numero1 + argp -> numero2;	

	return &result;
}

int *
resta_1_svc(calculadora *argp, struct svc_req *rqstp)
{
	printf("-------------------------\n");
	printf("    RESTA\n");
	printf("-------------------------\n");
	static int  result;

	/*
	 * insert server code here
	 */
	result = argp -> numero1 - argp -> numero2;

	return &result;
}

int *
multiplicacion_1_svc(calculadora *argp, struct svc_req *rqstp)
{
	printf("-------------------------\n");
	printf("    MULTIPLICACION\n");
	printf("-------------------------\n");
	static int  result;

	/*
	 * insert server code here
	 */
	result = argp -> numero1 * argp -> numero2;

	return &result;
}

float *
division_1_svc(calculadora *argp, struct svc_req *rqstp)
{
	printf("-------------------------\n");
	printf("    DIVISION\n");
	printf("-------------------------\n");
	static float  result;

	/*
	 * insert server code here
	 */
	result = argp -> numero1 / argp -> numero2;

	return &result;
}
